name: softgym
channels:
  - defaults
dependencies:
  - numpy
  - imageio
  - glob2
  - pybind11
  - click
  - matplotlib
  - joblib
  - Pillow
  - plotly
  - pip:
    - gymnasium
    - moviepy
    - opencv-python
    - Shapely
    - pyquaternion
    - sk-video
